### ISSUE TITLE
Exception when run with combined photos turned off

### ISSUE THREAD

**Issue by jzplusplus** [hatobi/bereal-gdpr-photo-toolkit#16]
Traceback (most recent call last):
  File "C:\Users\jzplusplus\Documents\bereal-gdpr-photo-toolkit\process-photos.py", line 451, in <module>
    remove_backup_files(output_folder_combined)
  File "C:\Users\jzplusplus\Documents\bereal-gdpr-photo-toolkit\process-photos.py", line 308, in remove_backup_files
    for filename in os.listdir(directory):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Photos\\post\\__combined'

Can be fixed with something like this:

`
if create_combined_images == 'yes':
    remove_backup_files(output_folder_combined)
`

**Comment by hatobi** [comment]
Thanks for catching the exception and providing a solution — I completely missed it! I’ve implemented the fix in the latest commit and credited you as a co-author.
